[tool.poetry]
name = "siti-tools"
version = "0.1.3"
description = ""
authors = ["Werner Robitza <werner.robitza@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8,<3.11"
numpy = "~=1.22.2"
scipy = "~=1.8.0"
av = "~=8.1.0"
tqdm = "~=4.62.3"
plotille = "~=4.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
flake8 = "^4.0.1"
black = "^22.3.0"
requests = "^2.27.1"
pytest-xdist = "^2.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
